In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
parkinson_data = pd.read_csv('parkinson_data.csv')
parkinson_data

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0        0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1        0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2        0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3        0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4        0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   
..           ...      ...     ...     ...       ...       ...       ...   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
0    0.266482  2.301442  0.284654  
1    0.335590  2.486855  0.368674  
2    0.311173  2.342259  0.332634  
3    0.334147  2.405554  0.368975  
4    0.234513  2.332180  0.410335  
..        ...       ...       ...  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[195 rows x 24 columns]

In [6]:
X = parkinson_data.drop(['status', 'name'], axis = 1)

In [8]:
y = parkinson_data['status']

In [ ]:
X = Xtrain, Xtext
y = ytrain, ytest

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 223)

In [26]:
model = LogisticRegression()

In [29]:
model.fit(X_train, y_train)

C:\Users\JB479JV\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
X_test

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
19       156.405       189.398       142.822         0.00768   
73       112.014       588.518       107.024         0.00533   
180      150.440       163.441       144.736         0.00396   
51       126.344       134.231       112.773         0.00448   
38       180.198       201.249       175.456         0.00284   
89       179.711       225.930       144.878         0.00709   
7        107.332       113.840       104.315         0.00290   
188      114.563       119.167        86.647         0.00327   
29       162.568       198.346        77.630         0.00502   
81        95.605       107.715        87.549         0.00702   
138      112.239       126.609       104.095         0.00472   
143      202.805       231.508        86.232         0.00370   
107      151.884       157.765       133.751         0.00258   
88       173.898       211.350        74.677         0.00448   
15       142.167       217.455        83.159         0.00369   
154      119.100       128.442        88.833         0.00692   
64       229.401       252.221       221.156         0.00205   
77       110.568       125.394       106.821         0.00462   
119      217.116       233.481        93.978         0.00404   
155      117.870       127.349        95.654         0.00647   
152      198.116       233.099       174.478         0.02714   
177      151.737       190.204       129.859         0.00314   
32       198.383       215.203       193.104         0.00212   
193      198.764       396.961        74.904         0.00740   
109      193.030       208.900        80.297         0.00766   
98       125.791       140.557        96.206         0.01378   
84       176.858       205.560        75.344         0.00747   
192      174.688       240.005        74.287         0.01360   
92       148.272       164.989       142.299         0.00459   
74       110.793       128.101       107.316         0.00494   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
19           0.000050   0.00372   0.00399     0.01116       0.03995   
73           0.000050   0.00268   0.00329     0.00805       0.02448   
180          0.000030   0.00206   0.00233     0.00619       0.02551   
51           0.000040   0.00131   0.00169     0.00393       0.02033   
38           0.000020   0.00153   0.00166     0.00459       0.01444   
89           0.000040   0.00391   0.00419     0.01172       0.04313   
7            0.000030   0.00144   0.00182     0.00431       0.01567   
188          0.000030   0.00146   0.00184     0.00439       0.01185   
29           0.000030   0.00280   0.00253     0.00841       0.01791   
81           0.000070   0.00428   0.00371     0.01283       0.03156   
138          0.000040   0.00238   0.00290     0.00715       0.05643   
143          0.000020   0.00189   0.00211     0.00568       0.01997   
107          0.000020   0.00115   0.00122     0.00346       0.01450   
88           0.000030   0.00237   0.00254     0.00710       0.06727   
15           0.000030   0.00157   0.00203     0.00471       0.01503   
154          0.000060   0.00393   0.00300     0.01179       0.02682   
64           0.000009   0.00114   0.00113     0.00342       0.01457   
77           0.000040   0.00226   0.00280     0.00677       0.02199   
119          0.000020   0.00127   0.00128     0.00381       0.01299   
155          0.000050   0.00356   0.00300     0.01067       0.03087   
152          0.000140   0.01568   0.01699     0.04705       0.08684   
177          0.000020   0.00135   0.00162     0.00406       0.01469   
32           0.000010   0.00113   0.00135     0.00339       0.01263   
193          0.000040   0.00370   0.00390     0.01109       0.02296   
109          0.000040   0.00450   0.00389     0.01351       0.03044   
98           0.000110   0.00826   0.00655     0.02478       0.04689   
84           0.000040   0.00418   0.00420     0.01254       0.04795   
192          0.000080   0.00624 

In [42]:
pred_values = model.predict(X_test)
pred_values

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [43]:
actual_values = np.array(y_test)
actual_values

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [37]:
pred == actual_values

array([ True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True])

In [38]:
len(actual_values)

30

In [39]:
26/30

0.8666666666666667

In [46]:
model.score(y_test, model.predict(X_test))

ValueError: Expected 2D array, got 1D array instead:
array=[1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.